/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UdhaarRouteImport } from './routes/udhaar'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'

const UdhaarRoute = UdhaarRouteImport.update({
  id: '/udhaar',
  path: '/udhaar',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/stock': typeof StockRoute
  '/udhaar': typeof UdhaarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/stock': typeof StockRoute
  '/udhaar': typeof UdhaarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/stats': typeof StatsRoute
  '/stock': typeof StockRoute
  '/udhaar': typeof UdhaarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile' | '/stats' | '/stock' | '/udhaar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/stats' | '/stock' | '/udhaar'
  id: '__root__' | '/' | '/profile' | '/stats' | '/stock' | '/udhaar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  StatsRoute: typeof StatsRoute
  StockRoute: typeof StockRoute
  UdhaarRoute: typeof UdhaarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/udhaar': {
      id: '/udhaar'
      path: '/udhaar'
      fullPath: '/udhaar'
      preLoaderRoute: typeof UdhaarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  StatsRoute: StatsRoute,
  StockRoute: StockRoute,
  UdhaarRoute: UdhaarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
